//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuplexApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuplexApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;us-ascii&quot;?&gt;
        ///&lt;SuplexStore xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;UIElements&gt;
        ///    &lt;UIElement&gt;
        ///      &lt;Id&gt;2ee2ab1b-c54e-4312-b6d6-db24d090711c&lt;/Id&gt;
        ///      &lt;Name&gt;fmEditor&lt;/Name&gt;
        ///      &lt;ControlType&gt;UserControl&lt;/ControlType&gt;
        ///      &lt;UniqueName&gt;fmEditor&lt;/UniqueName&gt;
        ///      &lt;DescTooltip&gt;false&lt;/DescTooltip&gt;
        ///      &lt;AllowUndeclared&gt;false&lt;/AllowUndeclared&gt;
        ///      &lt;DataType&gt;Empty&lt;/DataType&gt;
        ///      &lt;ValidationRules /&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fm {
            get {
                return ResourceManager.GetString("fm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;us-ascii&quot;?&gt;
        ///&lt;SuplexStore xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;UIElements&gt;
        ///    &lt;UIElement&gt;
        ///      &lt;Id&gt;026d585b-3404-483d-b9f4-0df889a76acd&lt;/Id&gt;
        ///      &lt;Name&gt;securityPrincipalEditor&lt;/Name&gt;
        ///      &lt;ControlType&gt;UserControl&lt;/ControlType&gt;
        ///      &lt;UniqueName&gt;securityPrincipalEditor&lt;/UniqueName&gt;
        ///      &lt;Desc /&gt;
        ///      &lt;DescTooltip&gt;false&lt;/DescTooltip&gt;
        ///      &lt;AllowUndeclared&gt;false&lt;/AllowUndeclared&gt;
        ///      &lt;DataType&gt;Str [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp {
            get {
                return ResourceManager.GetString("sp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;us-ascii&quot;?&gt;
        ///&lt;SuplexStore xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;UIElements&gt;
        ///    &lt;UIElement&gt;
        ///      &lt;Id&gt;2086302a-f858-4e19-8da0-9fc380de9ede&lt;/Id&gt;
        ///      &lt;Name&gt;UIE Editor Control&lt;/Name&gt;
        ///      &lt;ControlType&gt;UserControl&lt;/ControlType&gt;
        ///      &lt;UniqueName&gt;uieEditor&lt;/UniqueName&gt;
        ///      &lt;Desc /&gt;
        ///      &lt;DescTooltip&gt;false&lt;/DescTooltip&gt;
        ///      &lt;AllowUndeclared&gt;false&lt;/AllowUndeclared&gt;
        ///      &lt;DataType&gt;Empty&lt;/DataType&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uie {
            get {
                return ResourceManager.GetString("uie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;us-ascii&quot;?&gt;
        ///&lt;SuplexStore xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;UIElements&gt;
        ///    &lt;UIElement&gt;
        ///      &lt;Id&gt;549f74aa-ce16-43c9-a72a-6a0e5196c3fc&lt;/Id&gt;
        ///      &lt;Name&gt;logicRuleCtrl&lt;/Name&gt;
        ///      &lt;ControlType&gt;UserControl&lt;/ControlType&gt;
        ///      &lt;UniqueName&gt;logicRuleCtrl&lt;/UniqueName&gt;
        ///      &lt;Desc /&gt;
        ///      &lt;DescTooltip&gt;false&lt;/DescTooltip&gt;
        ///      &lt;AllowUndeclared&gt;false&lt;/AllowUndeclared&gt;
        ///      &lt;DataType&gt;Empty&lt;/DataType&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vr {
            get {
                return ResourceManager.GetString("vr", resourceCulture);
            }
        }
    }
}
