USE [master]
GO

/****** Object:  Database [Suplex]    Script Date: 08/16/2010 22:13:18 ******/
CREATE DATABASE [Suplex] ON  PRIMARY 
( NAME = N'Suplex_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Suplex.MDF' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 80KB )
 LOG ON 
( NAME = N'Suplex_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Suplex.LDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [Suplex] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Suplex].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [Suplex] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Suplex] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Suplex] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Suplex] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Suplex] SET ARITHABORT OFF 
GO

ALTER DATABASE [Suplex] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Suplex] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Suplex] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [Suplex] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Suplex] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Suplex] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Suplex] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Suplex] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Suplex] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Suplex] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Suplex] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Suplex] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Suplex] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Suplex] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Suplex] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Suplex] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Suplex] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Suplex] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Suplex] SET  READ_WRITE 
GO

ALTER DATABASE [Suplex] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Suplex] SET  MULTI_USER 
GO

ALTER DATABASE [Suplex] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [Suplex] SET DB_CHAINING OFF 
GO

