//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplex.WebForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suplex.WebForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordManagerImage {
            get {
                object obj = ResourceManager.GetObject("RecordManagerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordManagerImage1 {
            get {
                object obj = ResourceManager.GetObject("RecordManagerImage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SynchronizationManagerImage {
            get {
                object obj = ResourceManager.GetObject("SynchronizationManagerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon SyncManagerIcon {
            get {
                object obj = ResourceManager.GetObject("SyncManagerIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function selectTab(tabStrip,newBtn,newTab,cssNormal) {
        ///			if( tabStrip.lastTab ) {
        ///				tabStrip.lastTabButton.className = cssNormal;
        ///				tabStrip.lastTab.style.display = &apos;none&apos;;
        ///			}
        ///
        ///			newBtn.className = cssSelected;
        ///			newTab.style.display = &apos;&apos;;
        ///			tabStrip.lastTabButton = newBtn;
        ///			tabStrip.lastTab = newTab;
        ///		}
        ///
        ///		function doHover(cell,cssSelected,cssHover) {
        ///			if(cell.className != cssSelected)
        ///				cell.className = cssHover;
        ///		}
        ///
        ///		function doHoverOut(cell,cssSelected,cssNormal) {
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tableTabs_js {
            get {
                return ResourceManager.GetString("tableTabs_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tab-pane {
        ///	WIDTH: 100%; POSITION: relative
        ///}
        ///.dynamic-tab-pane-control .tab_row .tab {
        ///	BORDER-RIGHT: rgb(120,172,255) 1px solid; PADDING-RIGHT: 6px; BORDER-TOP: rgb(120,172,255) 0px solid; DISPLAY: inline; PADDING-LEFT: 6px; FONT-SIZE: 11px; Z-INDEX: 1; BACKGROUND: rgb(234,242,255); FLOAT: left; PADDING-BOTTOM: 3px; MARGIN: 1px -5px 1px 5px; BORDER-LEFT: rgb(120,172,255) 0px solid; CURSOR: pointer; PADDING-TOP: 3px; BORDER-BOTTOM: rgb(120,172,255) 0px solid; FONT-FAMILY: Verdana, Helvetica, Arial; PO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tabstrip_css_blue {
            get {
                return ResourceManager.GetString("tabstrip_css_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tab-pane {
        ///	WIDTH: 100%; POSITION: relative
        ///}
        ///.dynamic-tab-pane-control .tab-row .tab {
        ///	BORDER-RIGHT: threeddarkshadow 1px solid; PADDING-RIGHT: 5px; BORDER-TOP: buttonhighlight 1px solid; DISPLAY: inline; PADDING-LEFT: 5px; Z-INDEX: 1; BACKGROUND: buttonface; FLOAT: left; PADDING-BOTTOM: 3px; MARGIN: 1px -2px 1px 2px; FONT: Menu; BORDER-LEFT: buttonhighlight 1px solid; CURSOR: default; PADDING-TOP: 2px; BORDER-BOTTOM: threeddarkshadow 0px solid; POSITION: relative; TOP: 0px
        ///}
        ///.dynamic-tab-pane-cont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tabstrip_css_gray {
            get {
                return ResourceManager.GetString("tabstrip_css_gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*----------------------------------------------------------------------------\
        ///|                               Tab Pane 1.02                                 |
        ///|-----------------------------------------------------------------------------|
        ///|                         Created by Erik Arvidsson                           |
        ///|                  (http://webfx.eae.net/contact.html#erik)                   |
        ///|                      For WebFX (http://webfx.eae.net/)                      |
        ///|------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tabstrip_js {
            get {
                return ResourceManager.GetString("tabstrip_js", resourceCulture);
            }
        }
    }
}
